### ISSUE TITLE
`init` fails to generate a new matrix when a matrix is already loaded

### ISSUE THREAD

**Issue by charlesdaniels** [charlesdaniels/hercm#30]
Console log demonstrating the error. This was generated after load bcsstk01.mtx

```
> info
- matrix properties -
height (number of rows) - 0
width (number of cols)  - 0
non zero elements - - - - 176
symmetry  - - - - - - - - SYM
verification  - - - - - - 1
- end matrix properties -
> coodisplay
- raw matrix contents -
row    col    val
     3      1 -2000000.0
     3      2 -2083333.33333
     4      0 1000000.0
     4      2 -2777777.77778
     5      0 2083333.33333
     5      1 5555555.55555
     6      0 -3333.33333333
     6      4 -1000000.0
     7      1 -6666.66666667
     7      3 2000000.0
     8      2 -1680000.0
     9      1 -2000000.0
     9      3 400000000.0
     9      7 2000000.0
     9      8 -2083333.33333
    10      0 1000000.0
    10      4 200000000.0
    10      6 -1000000.0
    10      8 -2777777.77778
    11      5 -2000000.0
    11      6 2083333.33333
    11      7 5555555.55555
    12      6 -2800000.0
    13      7 -30864.1975309
    13     11 -5555555.55555
    14      8 -15432.0987654
    14     10 2777777.77778
    14     13 517922.131816
    15      9 -3333333.33333
    15     13 4298570.58902
    15     14 -2634990.2747
    16      8 -2777777.77778
    16     10 333333333.333
    16     12 -2149285.29451
    16     14 2777777.77778
    17      7 5555555.55555
    17     11 666666666.667
    17     12 2359161.80402
    17     13 -5555555.55555
    17     16 -109779731.332
    18      0 -2800000.0
    18     12 -3333.33333333
    18     16 1000000.0
    19      1 -30864.1975309
    19      5 -5555555.55555
    19     13 -6666.66666667
    19     15 -2000000.0
    20      2 -15432.0987654
    20      4 2777777.77778
    20     14 -1680000.0
    21      3 -3333333.33333
    21     13 2000000.0
    21     15 400000000.0
    21     19 -2000000.0
    21     20 -2083333.33333
    22      2 -2777777.77778
    22      4 333333333.333
    22     12 -1000000.0
    22     16 200000000.0
    22     18 1000000.0
    22     20 2777777.77778
    23      1 5555555.55555
    23      5 666666666.667
    23     17 -2000000.0
    23     18 2083333.33333
    23     19 -5555555.55555
    24      0 -28935.1851852
    24      5 -2083333.33333
    25      1 -1597916.66667
    26      2 -28935.1851852
    26      3 2083333.33333
    27      2 -2083333.33333
    27      3 100000000.0
    27     25 -2500000.0
    27     26 -416666.666667
    28      4 -833333.333333
    28     24 1250000.0
    29      0 2083333.33333
    29      5 100000000.0
    29     24 416666.666667
    30      6 -28935.1851852
    30     11 -2083333.33333
    30     24 -4166.66666667
    30     28 -1250000.0
    31      7 -1597916.66667
    31     25 -8333.33333333
    31     27 2500000.0
    32      8 -28935.1851852
    32      9 2083333.33333
    32     26 -2355000.0
    33      8 -2083333.33333
    33      9 100000000.0
    33     25 -2500000.0
    33     27 500000000.0
    33     31 2500000.0
    33     32 -416666.666667
    34     10 -833333.333333
    34     24 1250000.0
    34     28 250000000.0
    34     30 -1250000.0
    34     32 -3472222.22222
    35      6 2083333.33333
    35     11 100000000.0
    35     29 -2500000.0
    35     30 416666.666667
    35     31 6944444.44444
    36     12 -28935.1851852
    36     17 -2083333.33333
    36     30 -3925000.0
    37     13 -1597916.66667
    37     31 -38580.2469136
    37     35 -6944444.44444
    38     14 -28935.1851852
    38     15 2083333.33333
    38     32 -19290.1234568
    38     34 3472222.22222
    39     14 -2083333.33333
    39     15 100000000.0
    39     33 -4166666.66667
    39     37 2500000.0
    39     38 -416666.666667
    40     16 -833333.333333
    40     32 -3472222.22222
    40     34 416666666.667
    40     36 -1250000.0
    40     38 3472222.22222
    41     12 2083333.33333
    41     17 100000000.0
    41     31 6944444.44445
    41     35 833333333.333
    41     36 416666.666667
    41     37 -6944444.44445
    42     12 -3830.95098171
    42     16 1149285.29451
    42     17 -275828.470683
    42     18 -28935.1851852
    42     23 -2083333.33333
    42     36 -4166.66666667
    42     40 1250000.0
    43     13 -131963.213599
    43     14 -517922.131816
    43     15 -2298570.58902
    43     19 -1597916.66667
    43     37 -8333.33333333
    43     39 -2500000.0
    44     13 -517922.131816
    44     14 -2165670.78453
    44     15 551656.941366
    44     20 -28935.1851852
    44     21 2083333.33333
    44     38 -2355000.0
    44     43 517922.131816
    45     13 2298570.58902
    45     14 -551656.941367
    45     15 486193650.99
    45     20 -2083333.33333
    45     21 100000000.0
    45     37 2500000.0
    45     39 500000000.0
    45     43 -4798570.58902
    45     44 134990.2747
    46     12 -1149285.29451
    46     16 229724661.236
    46     17 -55717351.0779
    46     22 -833333.333333
    46     36 -1250000.0
    46     40 250000000.0
    46     42 2399285.29451
    47     12 275828.470683
    47     16 -55717351.0779
    47     17 10941196.0038
    47     18 2083333.33333
    47     23 100000000.0
    47     41 -2500000.0
    47     42 140838.195984
    47     46 -109779731.332
> init 5 5
WARNING:root:Command halted because of exception: newRow out of bounds
> traceback
Traceback (most recent call last):
  File "HercExplorer.py", line 123, in main
    NEWWM = item.execute(arguments, WORKINGMATRIX)
  File "/Users/cad/Documents/Personal/Projects/hercm/src/python33/menuPlugins/init.py", line 29, in execute
    MatrixUtils.initialize(height, width, WORKINGMATRIX, val)
  File "/Users/cad/Documents/Personal/Projects/hercm/src/python33/MatrixUtils.py", line 400, in initialize
    setDims(0, 0, HERCMATRIX)
  File "/Users/cad/Documents/Personal/Projects/hercm/src/python33/MatrixUtils.py", line 373, in setDims
    HERCMATRIX.elements['col'][i], 0)
  File "/Users/cad/Documents/Personal/Projects/hercm/src/python33/libHercMatrix.py", line 331, in setValue
    raise IndexError("newRow out of bounds")
IndexError: newRow out of bounds
```

**Comment by charlesdaniels** [comment]
Resolved in     f076637
